data:

  - code_adherent: "00475"
    nom: "Zion"
    prenom: "Eva"
    date_naissance: "2003-04-29"
    civilite: True

  - code_adherent: "00476"
    nom: "Gole"
    prenom: "Henry"
    date_naissance: "2001-03-19"
    civilite: False