data:

  - code_adherent: "00475"
    code_isbn: "0156195445"
    date_heure_debut: ""
    date_heure_fin: null

  - code_adherent: "00476"
    code_isbn: "0750878851"
    date_heure_debut: 0
    date_heure_fin: null